### ISSUE TITLE
Any ideas on how to fix buffer overflows?

### ISSUE THREAD

**Issue by cmh716** [charlie-foxtrot/RTLSDR-Airband#488]
**Describe your environment**
* Latest main branch
* Tried on RPi 5 and x86 Core i5 CPU (NUC 11th Generation)

**What happened?**
I am trying to use a Rigexpert Fobos SDR with the Soapy Drivers, but I get buffer overruns with sample rates over 20Ms

**What you expected to happen?**
I can capture 20Ms on the RPI 5, but I get constant buffer overflows if I go to 25-50. It could be because the CPU cannot handle it. but the Core i5 cannot run higher sample rates either despite using only 8% CPU.

**Your rtl_airband.conf file**
```
multiple_demod_threads = true;
multiple_output_threads = true;
devices:
(

{
  type = "soapysdr";
   device_string = "driver=fobos,serial=A1D610000XXX,lna_gain=3,vga_gain=10";
   sample_rate = 30000000;
   gain = 60;
   centerfreq = 150.00;
   #correction = 10;
   channels:
   (
         {
           freq = 146.38;
           label = "Test1";
           modulation = "nfm";
           bandwidth = 5000;
           outputs: (
                   {
                   type = "file";
                   directory = "/build";
                   filename_template = "Fobos1";
           #   continuous = false;
                   split_on_transmission = true;
                   include_freq = true;
           #   append = true;
                   dated_subdirectories = true;
                 }
```

**Comment by gabeschine** [comment]
I'm no expert. It may be that you are encountering buffer overflows because of the sheer volume of data that is necessary to move from the SDR to your computer in your use-case. It could be a problem for the USB bus? If you absolutely cannot reduce the sample rate, are there other things you could change, such as moving to 8-bit sampling over (is it 12-bit for the Fobos by default?).

Again, no expert, just throwing some ideas out that might get you moving in the right direction.
